exclude: [tools, MIGRATION.md]
remote_theme: just-the-docs/just-the-docs
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-feed
domain: www.openutau.com
url: https://www.openutau.com
color_scheme: openutau
aux_links:
  "GitHub":
    - "https://github.com/openutau/OpenUtau"
nav_external_links:
  - title: Discussions / 讨论 / 議論
    url: https://github.com/openutau/OpenUtau/discussions
    hide_icon: false
  - title: Report Bugs / 问题汇报 / 不具合報告
    url: https://github.com/openutau/OpenUtau/issues
    hide_icon: false
  - title: Discord
    url: https://discord.gg/UfpMnqMmEM
    hide_icon: false
